AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  new-project

Globals: 
  Function:
    Timeout: 3
    Runtime: python3.10
    MemorySize: 128
    Environment:
      Variables:
        FILE_TABLE: !Ref FileTable
        FILE_BUCKET: !Ref FileBucket

Resources:
  FileTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  FileBucket:
    Type: AWS::S3::Bucket
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: orders_api/
      Handler: create.lambda_handler
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: post
  UploadFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3_handlers/
      Handler: upload.lambda_handler
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FileBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref FileTable
      Events:
        UploadFile:
          Type: Api
          Properties:
            Path: /upload
            Method: post
  ReadFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3_handlers/
      Handler: read.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref FileBucket
      Events:
        ReadFile:
          Type: Api
          Properties:
            Path: /read
            Method: get
